%
% Name
%   mms_edi_write_ql_efield
%
% Purpose
%   Create a MATLAB save file of inputs needed for Bestarg.
%
% Calling Sequence
%   EDI_QL_FILE = mms_edi_write_ql_efield(EDI_QL)
%     Write EDI quick-look data constained in the structure EDI_QL
%     and created by mms_edi_create_ql_efield.m to a CDF file named
%     EDI_QL_FILE.
%
% Parameters
%   EDI_QL:         in, required, type=string
%
% Returns
%   EDI_QL_FILE     out, required, type=string
%
% MATLAB release(s) MATLAB 7.14.0.739 (R2012a)
% Required Products None
%
% History:
%   2015-06-20      Written by Matthew Argall
%   2015-07-20      Updated to v0.1.4. Corrected sign of E, added Quality, fixed
%                     attributes. Renamed from mms_sdc_edi_write_ql_efield to
%                     mms_edi_write_ql_efield - MRA
%
function edi_ql_file = mms_edi_write_ql_efield(edi_ql)
%------------------------------------%
% Create CDF File                    %
%------------------------------------%
	% Extract for ease of use
	sc      = edi_ql.sc;
	instr   = edi_ql.instr;
	mode    = edi_ql.mode;
	level   = 'ql';
	optdesc = edi_ql.optdesc;
	tstart  = edi_ql.tstart;

	% convert the start time to yyyy-mm-dd
	tstart = MrTimeParser(tstart, '%Y-%M-%dT%H:%m:%S', '%Y%M%d');
	                                  
	% Describe the modifications to each version
	version = 'v0.1.4';
	mods    = {  'v0.0.0 -- First version.', ...
	             'v0.0.1 -- Added gun positions.', ...
	             'v0.0.2 -- Include points with beams from single gun.', ...
	             'v0.1.0 -- Add weighting factor to beam convergence.', ...
	            ['v0.1.1 -- Added delta_plus and delta_minus variables. ' ...
	                        '0-based indices. Drift step has correct units.'], ...
	            ['v0.1.2 -- Added "recnum" variables.'], ...
	            ['v0.1.3 -- Update calculations of delta_d, v_ExB, and E.'], ...
	            ['v0.1.4 -- Corrected sign of E. Added quality. ' ... 
	                        'VAR_TYPE and "Generated_by" attributes fixed.'] ...
	          };

	% Create the output filename
	edi_ql_file = mms_construct_filename(sc, instr, mode, level, ...
	                                     'Directory', edi_ql.directory, ...
	                                     'OptDesc',   optdesc, ...
	                                     'TStart',    tstart, ...
	                                     'Version',   version);

%------------------------------------------------------
% Global Attributes                                   |
%------------------------------------------------------
	if isempty(optdesc)
		data_type      = [mode '_' level];
		logical_source = [instr '_' mode '_' level];
	else
		data_type      = [mode '_' level '_' optdesc];
		logical_source = [instr '_' mode '_' level '_' optdesc];
	end
	[~, logical_file_id, ext] = fileparts(edi_ql_file);
	logical_file_id = [logical_file_id ext];

	%   - Instrument Type (1+)
	%           Electric Fields (space)
	%           Magnetic Fields (space)
	%           Particles (space)
	%           Plasma and Solar Wind
	%           Spacecraft Potential Control
	global_attrs = struct( 'Data_type',                  data_type, ...
	                       'Data_version',               version, ...
	                       'Descriptor',                 'EDI', ...
	                       'Discipline',                 'Space Physics>Magnetospheric Science', ...
	                       'Generation_date',            datestr(now(), 'yyyymmdd'), ...
	                       'Instrument_type',            'Magnetic Fields (space)', ...
	                       'Logical_file_id',            logical_file_id, ...
	                       'Logical_source',             logical_source, ...
	                       'Logical_source_description', ' ', ...
	                       'Mission_group',              'MMS', ...
	                       'PI_affiliation',             'SWRI, UNH', ...
	                       'PI_name',                    'J. Burch, R. Torbert', ...
	                       'Project',                    'STP>Solar Terrestrial Physics', ...
	                       'Source_name',                'MMS#>MMS Satellite Number #', ...
	                       'TEXT',                       ['EDI electric field data. ' ...
	                                                      'Instrument papers for EDI can be found at: ' ...
	                                                      ''], ...
	                       'HTTP_LINK',                  { {'http://mms-fields.unh.edu/' ...
	                                                        'http://mms.gsfc.nasa.gov/index.html'} }, ...
	                       'LINK_TEXT',                  { {'UNH FIELDS Home Page', ...
	                                                        'NASA MMS Home'} }, ...
	                       'MODS',                       { mods }, ...
	                       'Acknowledgements',           ' ', ...
	                       'Generated_by',               'Matthew Argall (matthew.argall@unh.edu)', ...
	                       'Parents',                    { edi_ql.parents }, ...
	                       'Skeleton_version',           ' ', ...
	                       'Rules_of_use',               ' ', ...
	                       'Time_resolution',            ' '  ...
	                     );

%------------------------------------------------------
% Variables                                           |
%------------------------------------------------------
	% Variable naming convention
	%   scId_instrumentId_paramName_optionalDescriptor
	tt2000_vname      = 'Epoch';
	dtt2000_vname     = 'Epoch_delta_plus';
	e_vname           = mms_construct_varname(sc, instr, 'E', 'dmpa');
	v_vname           = mms_construct_varname(sc, instr, 'v', 'ExB_dmpa');
	d_vname           = mms_construct_varname(sc, instr, 'd', 'dmpa');
	d_std_vname       = mms_construct_varname(sc, instr, 'd', 'std_dmpa');
	b_vname           = mms_construct_varname(sc, instr, 'B', 'dmpa');
	b_std_vname       = mms_construct_varname(sc, instr, 'B', 'std_dmpa');
	quality_vname     = mms_construct_varname(sc, instr, 'quality' );
	
	% Axis labels
	e_labl_vname  = 'E_Labl_Ptr';
	v_labl_vname  = 'v_Labl_Ptr';
	d_labl_vname  = 'd_Labl_Ptr';
	b_labl_vname  = 'B_Labl_Ptr';
	vg_labl_vname = 'vg_labl_vname';
	
	% Beam Variables
	t_gd12_vname      = 'epoch_gd12_beam';
	t_gd21_vname      = 'epoch_gd21_beam';
	pos_vg1_vname     = mms_construct_varname(sc, instr, 'pos',          'virtual_gun1_dmpa');
	pos_vg2_vname     = mms_construct_varname(sc, instr, 'pos',          'virtual_gun2_dmpa');
	fv_gd12_vname     = mms_construct_varname(sc, instr, 'fv',           'gd12_dmpa');
	fv_gd21_vname     = mms_construct_varname(sc, instr, 'fv',           'gd21_dmpa');
	recnum_vname      = mms_construct_varname(sc, instr, 'recnum');
	recnum_gd12_vname = mms_construct_varname(sc, instr, 'recnum',       'gd12');
	recnum_gd21_vname = mms_construct_varname(sc, instr, 'recnum',       'gd21');
	q_beam_gd12_vname = mms_construct_varname(sc, instr, 'beam_quality', 'gd12');
	q_beam_gd21_vname = mms_construct_varname(sc, instr, 'beam_quality', 'gd21');

	% Variable Data
	var_list = { tt2000_vname,       edi_ql.tt2000, ...
	             dtt2000_vname,      edi_ql.dt, ...
	             t_gd12_vname,       edi_ql.tt2000_gd12, ...
	             t_gd21_vname,       edi_ql.tt2000_gd21, ...
	             e_vname,            single(edi_ql.E_dmpa), ...
	             v_vname,            single(edi_ql.v_dmpa), ...
	             d_vname,            single(edi_ql.d_dmpa), ...
	             b_vname,            single(edi_ql.B_dmpa), ...
	             quality_vname,      edi_ql.quality, ...
	             pos_vg1_vname,      single(edi_ql.pos_vg1_dmpa), ...
	             pos_vg2_vname,      single(edi_ql.pos_vg2_dmpa), ...
	             fv_gd12_vname,      single(edi_ql.fv_gd12_dmpa), ...
	             fv_gd21_vname,      single(edi_ql.fv_gd21_dmpa), ...
	             recnum_vname,       edi_ql.recnum, ...
	             recnum_gd12_vname,  edi_ql.recnum_gd12, ...
	             recnum_gd21_vname,  edi_ql.recnum_gd21, ...
	             q_beam_gd12_vname,  int8(edi_ql.quality_gd12), ...
	             q_beam_gd21_vname,  int8(edi_ql.quality_gd21), ...
	             d_std_vname,        edi_ql.d_std_dmpa, ...
	             b_std_vname,        edi_ql.B_std_dmpa, ...
	             e_labl_vname,       {'Ex'; 'Ey'; 'Ez'}, ...
	             v_labl_vname,       {'vx'; 'vy'; 'vz'}, ...
	             d_labl_vname,       {'dx'; 'dy'; 'dz'}, ...
	             b_labl_vname,       {'Bx'; 'By'; 'Bz'}, ...
	             vg_labl_vname,      {'x'; 'y'; 'z'} ...
	           };

	% Record Variance
	recbound = { tt2000_vname, ...
	             t_gd12_vname, ...
	             t_gd21_vname, ...
	             e_vname, ...
	             v_vname, ...
	             d_vname, ...
	             d_std_vname, ...
	             b_vname, ...
	             b_std_vname, ...
	             quality_vname, ...
	             pos_vg1_vname, ...
	             pos_vg2_vname, ...
	             fv_gd12_vname, ...
	             fv_gd21_vname, ...
	             recnum_vname, ...
	             recnum_gd12_vname, ...
	             recnum_gd21_vname, ...
	             q_beam_gd12_vname, ...
	             q_beam_gd21_vname, ...
	           };

	% Data types
	vardatatypes = { tt2000_vname,       'cdf_time_tt2000', ...
	                 dtt2000_vname,      'cdf_time_tt2000', ...
	                 t_gd12_vname,       'cdf_time_tt2000', ...
	                 t_gd21_vname,       'cdf_time_tt2000', ...
	                 e_vname,            'cdf_float', ...
	                 v_vname,            'cdf_float', ...
	                 d_vname,            'cdf_float', ...
	                 d_std_vname,        'cdf_float', ...
	                 b_vname,            'cdf_float', ...
	                 b_std_vname,        'cdf_float', ...
	                 quality_vname,      'cdf_int1',  ...
	                 pos_vg1_vname,      'cdf_float', ...
	                 pos_vg1_vname,      'cdf_float', ...
	                 fv_gd12_vname,      'cdf_float', ...
	                 fv_gd21_vname,      'cdf_float', ...
	                 recnum_vname,       'cdf_int4', ...
	                 recnum_gd12_vname,  'cdf_int4', ...
	                 recnum_gd21_vname,  'cdf_int4', ...
	                 q_beam_gd12_vname,  'cdf_int1', ...
	                 q_beam_gd21_vname,  'cdf_int1', ...
	                 e_labl_vname,       'cdf_char', ...
	                 v_labl_vname,       'cdf_char', ...
	                 d_labl_vname,       'cdf_char', ...
	                 b_labl_vname,       'cdf_char', ...
	                 vg_labl_vname,      'cdf_char' ...
	               };
	

%------------------------------------------------------
% Variable Attributes                                 |
%------------------------------------------------------
	%
	% This assignment fails because the cell arrays do not have the same
	% number of elements. Adding variable attributes will have to be done
	% with cdflib.
	%
	var_attrs = struct( 'CATDESC',     {  ...
	                                     { tt2000_vname,  'TT2000 time tags for EDI electric field data.', ...
	                                       dtt2000_vname, 'Upper bound for the time stamps.', ...
	                                       t_gd12_vname,  'TT2000 time tags for EDI GDU1 beam data.', ...
	                                       t_gd21_vname,  'TT2000 time tags for EDI GDU2 beam data.', ...
	                                       e_vname,      ['Electric field derived from EDI beam data ' ...
	                                                      'via the Triangulation and Time-of-Flight methods.'], ...
	                                       v_vname,      ['ExB drift velocity derived from EDI beam data ' ...
	                                                      'via the Triangulation and Time-of-Flight methods.'], ...
	                                       d_vname,      ['Drift step (distance an electron drifts in one gyro-period) ' ...
	                                                      'derived from EDI beam data via the Triangulation and ' ...
	                                                      'Time-of-Flight methods.'], ...
	                                       d_std_vname,   'Standard deviation of the drift step.', ...
	                                       b_vname,      ['5-second averaged magnetic field data used to define ' ...
	                                                      'the plane perpendicular to B, in which the Triangulation ' ...
	                                                      'method calculations are carried out.'], ...
	                                       b_std_vname,   'Standard deviation of the averaged magnetic field.', ...
	                                       quality_vname, 'Quality flag', ...
	                                       pos_vg1_vname, 'Position of gun1 on the virtual spacecraft.', ...
	                                       pos_vg2_vname, 'Position of gun2 on the virtual spacecraft.', ...
	                                       fv_gd12_vname, 'Firing vectors from the gun1-detector2 pair, in DMPA coordinates.', ...
	                                       fv_gd21_vname, 'Firing vectors from the gun2-detector1 pair, in DMPA coordinates.', ...
	                                       recnum_vname, ['Record number of each element of ' tt2000_vname '.'], ...
	                                       recnum_gd12_vname, ['The record number of ' b_vname ' to which each beam from GD12 maps.'], ...
	                                       recnum_gd21_vname, ['The record number of ' b_vname ' to which each beam from GD21 maps.'], ...
	                                       q_beam_gd12_vname, 'The quality of GD12 beams used to find the drift step.', ...
	                                       q_beam_gd21_vname, 'The quality of GD21 beams used to find the drift step.', ...
	                                       e_labl_vname,  'Axis labels for electric field', ...
	                                       v_labl_vname,  'Axis labels for drift velocity', ...
	                                       d_labl_vname,  'Axis labels for drift step.', ...
	                                       b_labl_vname,  'Axis labels for magnetic field.', ...
	                                       vg_labl_vname, 'Axis labels for virtual gun positions.' ...
	                                     } ...
	                                   }, ...
	                    'DEPEND_0',    {  ...
	                                     { e_vname,           tt2000_vname, ...
	                                       v_vname,           tt2000_vname, ...
	                                       d_vname,           tt2000_vname, ...
	                                       d_std_vname,       tt2000_vname, ...
	                                       b_vname,           tt2000_vname, ...
	                                       b_std_vname,       tt2000_vname, ...
	                                       quality_vname,     tt2000_vname, ...
	                                       pos_vg1_vname,     t_gd12_vname, ...
	                                       pos_vg2_vname,     t_gd21_vname, ...
	                                       fv_gd12_vname,     t_gd12_vname, ...
	                                       fv_gd21_vname,     t_gd21_vname, ...
	                                       recnum_vname,      tt2000_vname, ...
	                                       recnum_gd12_vname, t_gd12_vname, ...
	                                       recnum_gd21_vname, t_gd21_vname, ...
	                                       q_beam_gd12_vname, t_gd12_vname, ...
	                                       q_beam_gd21_vname, t_gd21_vname ...
	                                     } ...
	                                   }, ...
	                 'DELTA_PLUS_VAR', {  ...
	                                     { tt2000_vname, dtt2000_vname, ...
	                                       d_vname,      d_std_vname, ...
	                                       b_vname,      b_std_vname ...
	                                     } ...
	                                   }, ...
	                'DELTA_MINUS_VAR', {  ...
	                                     { d_vname,      d_std_vname, ...
	                                       b_vname,      b_std_vname ...
	                                     } ...
	                                   }, ...
	                    'DISPLAY_TYPE',  {  ... 
	                                       { e_vname,           'time_series', ...
	                                         v_vname,           'time_series', ...
	                                         d_vname,           'time_series', ...
	                                         b_vname,           'time_series', ...
	                                         pos_vg1_vname,     'time_series', ...
	                                         pos_vg2_vname,     'time_series', ...
	                                         fv_gd12_vname,     'time_series', ...
	                                         fv_gd21_vname,     'time_series' ...
	                                       } ...
	                                     }, ...
	                    'FIELDNAM',      {  ...
	                                       { tt2000_vname,      'Time', ...
	                                         dtt2000_vname,     'dt', ...
	                                         t_gd12_vname,      'Time', ...
	                                         t_gd21_vname,      'Time', ...
	                                         e_vname,           'Electric Field', ...
	                                         v_vname,           'ExB Drift Velocity', ...
	                                         d_vname,           'Drift Step', ...
	                                         d_std_vname,       'delta d', ...
	                                         b_vname,           'Magnetic Field', ...
	                                         b_std_vname,       'delta B', ...
	                                         quality_vname,     'Quality', ...
	                                         pos_vg1_vname,     'Gun Position', ...
	                                         pos_vg2_vname,     'Gun Position', ...
	                                         fv_gd12_vname,     'Firing vectors', ...
	                                         fv_gd21_vname,     'Firing vectors', ...
	                                         recnum_vname,      'Record', ...
	                                         recnum_gd12_vname, 'Record', ...
	                                         recnum_gd21_vname, 'Record', ...
	                                         q_beam_gd12_vname, 'GD12 beam quality', ...
	                                         q_beam_gd21_vname, 'GD21 beam quality', ...
	                                         e_labl_vname,      'Axis Labels', ...
	                                         v_labl_vname,      'Axis Labels', ...
	                                         d_labl_vname,      'Axis Labels', ...
	                                         b_labl_vname,      'Axis Labels', ...
	                                         vg_labl_vname,     'Axis Labels' ...
	                                       }
	                                     }, ...
	                    'FILLVAL',       {  ...
	                                       { tt2000_vname,  -1.0E31, ...
	                                         dtt2000_vname, -1.0E31, ...
	                                         t_gd12_vname,  -1.0E31, ...
	                                         t_gd21_vname,  -1.0E31, ...
	                                         e_vname,       single(-1.0E31), ...
	                                         v_vname,       single(-1.0E31), ...
	                                         d_vname,       single(-1.0E31), ...
	                                         d_std_vname,   single(-1.0E31), ...
	                                         b_vname,       single(-1.0E31), ...
	                                         b_std_vname,   single(-1.0E31), ...
	                                         pos_vg1_vname, single(-1.0E31), ...
	                                         pos_vg2_vname, single(-1.0E31), ...
	                                         fv_gd12_vname, single(-1.0E31), ...
	                                         fv_gd21_vname, single(-1.0E31) ...
	                                       } ...
	                                     }, ...
	                    'FORMAT',        {  ...
	                                       { tt2000_vname,      'I16',...
	                                         dtt2000_vname,     'I16',...
	                                         t_gd12_vname,      'I16',...
	                                         t_gd21_vname,      'I16',...
	                                         e_vname,           'F12.6', ...
	                                         v_vname,           'F12.6', ...
	                                         d_vname,           'F12.6', ...
	                                         d_std_vname,       'F12.6', ...
	                                         b_vname,           'F12.6', ...
	                                         b_std_vname,       'F12.6', ...
	                                         quality_vname,     'I1', ...
	                                         pos_vg1_vname,     'F12.6', ...
	                                         pos_vg2_vname,     'F12.6', ...
	                                         fv_gd12_vname,     'F12.6', ...
	                                         fv_gd21_vname,     'F12.6', ...
	                                         recnum_vname,      'I9', ...
	                                         recnum_gd12_vname, 'I9', ...
	                                         recnum_gd21_vname, 'I9', ...
	                                         q_beam_gd12_vname, 'I1', ...
	                                         q_beam_gd21_vname, 'I1', ...
	                                         e_labl_vname,      'A2', ...
	                                         v_labl_vname,      'A2', ...
	                                         d_labl_vname,      'A2', ...
	                                         b_labl_vname,      'A2', ...
	                                         vg_labl_vname,     'A1' ...
	                                       } ...
	                                     }, ...
	                    'LABLAXIS',      {  ...
	                                       { tt2000_vname,      'UT',...
	                                         t_gd12_vname,      'UT',...
	                                         t_gd21_vname,      'UT',...
	                                         quality_vname,     'Quality', ...
	                                         recnum_vname,      'Record', ...
	                                         recnum_gd12_vname, 'Record', ...
	                                         recnum_gd21_vname, 'Record', ...
	                                         q_beam_gd12_vname, 'Quality', ...
	                                         q_beam_gd21_vname, 'Quality' ...
	                                       } ...
	                                     }, ...
	                    'LABL_PTR_1',    {  ...
	                                       { e_vname,       e_labl_vname, ...
	                                         v_vname,       v_labl_vname, ...
	                                         d_vname,       d_labl_vname, ...
	                                         b_vname,       b_labl_vname, ...
	                                         pos_vg1_vname, vg_labl_vname, ...
	                                         pos_vg2_vname, vg_labl_vname ...
	                                       } ...
	                                     }, ...
	                    'SI_CONVERSION', {  ...
	                                       { tt2000_vname,  '1e-9>seconds',...
	                                         dtt2000_vname, '1e-9>seconds',...
	                                         t_gd12_vname,  '1e-9>seconds',...
	                                         t_gd21_vname,  '1e-9>seconds',...
	                                         e_vname,       '1e-3>Volts/meter', ...
	                                         v_vname,       '1e-3>meters/second', ...
	                                         d_vname,       '1e0>meters', ...
	                                         d_std_vname,   '1e0>meters', ...
	                                         b_vname,       '1e-9>Tesla', ...
	                                         b_std_vname,   '1e-9>Tesla', ...
	                                         pos_vg1_vname, '1e0>meters', ...
	                                         pos_vg2_vname, '1e0>meters', ...
	                                       } ...
	                                     }, ...
	                    'UNITS',         {  ...
	                                       { tt2000_vname,  'ns',...
	                                         dtt2000_vname, 'ns',...
	                                         t_gd12_vname,  'ns',...
	                                         t_gd21_vname,  'ns',...
	                                         e_vname,       'mV/m', ...
	                                         v_vname,       'km/s', ...
	                                         d_vname,       'm', ...
	                                         d_std_vname,   'm', ...
	                                         b_vname,       'nT' ...
	                                         b_std_vname,   'nT', ...
	                                         pos_vg1_vname, 'm', ...
	                                         pos_vg2_vname, 'm', ...
	                                       } ...
	                                     }, ...
	                    'VALIDMIN',      {  ...
	                                       { tt2000_vname,      cdflib.computeEpoch([2015, 3, 1, 0, 0, 0, 0]), ...
	                                         dtt2000_vname,     int32(0), ...
	                                         t_gd12_vname,      cdflib.computeEpoch([2015, 3, 1, 0, 0, 0, 0]), ...
	                                         t_gd21_vname,      cdflib.computeEpoch([2015, 3, 1, 0, 0, 0, 0]), ...
	                                         e_vname,           single(-100000.0), ...
	                                         v_vname,           single(-100000.0), ...
	                                         d_vname,           single(-100000.0), ...
	                                         d_std_vname,       single(-1000.0), ...
	                                         b_vname,           single(-100000.0), ...
	                                         b_std_vname,       single(-1000.0), ...
	                                         quality_vname,     uint8(0), ...
	                                         pos_vg1_vname,     single(20), ...
	                                         pos_vg2_vname,     single(20), ...
	                                         fv_gd12_vname,     single(-100000.0), ...
	                                         fv_gd21_vname,     single(-100000.0), ...
	                                         recnum_vname,      int32(0), ...
	                                         recnum_gd12_vname, int32(0), ...
	                                         recnum_gd21_vname, int32(0), ...
	                                         q_beam_gd12_vname, int8(0), ...
	                                         q_beam_gd21_vname, int8(0) ...
	                                       }
	                                     }, ...
	                    'VALIDMAX',      {  ...
	                                       { tt2000_vname,      cdflib.computeEpoch([2050, 3, 1, 0, 0, 0, 0]), ...
	                                         dtt2000_vname,     int32(2e10), ...
	                                         t_gd12_vname,      cdflib.computeEpoch([2050, 3, 1, 0, 0, 0, 0]), ...
	                                         t_gd21_vname,      cdflib.computeEpoch([2050, 3, 1, 0, 0, 0, 0]), ...
	                                         e_vname,           single(100000.0), ...
	                                         v_vname,           single(100000.0), ...
	                                         d_vname,           single(100000.0), ...
	                                         d_std_vname,       single(1000.0), ...
	                                         b_vname,           single(100000.0), ...
	                                         b_std_vname,       single(1000.0), ...
	                                         quality_vname,     uint8(3), ...
	                                         pos_vg1_vname,     single(-20), ...
	                                         pos_vg2_vname,     single(-20), ...
	                                         fv_gd12_vname,     single(100000.0), ...
	                                         fv_gd21_vname,     single(100000.0), ...
	                                         recnum_vname,      int32(4294967295), ...
	                                         recnum_gd12_vname, int32(4294967295), ...
	                                         recnum_gd21_vname, int32(4294967295), ...
	                                         q_beam_gd12_vname, int8(3), ...
	                                         q_beam_gd21_vname, int8(3) ...
	                                       }
	                                     }, ...
	                    'VAR_TYPE',      {  ...
	                                       { tt2000_vname,      'support_data', ...
	                                         dtt2000_vname,     'support_data', ...
	                                         t_gd12_vname,      'support_data', ...
	                                         t_gd21_vname,      'support_data', ...
	                                         e_vname,           'data', ...
	                                         v_vname,           'data', ...
	                                         d_vname,           'data', ...
	                                         d_std_vname,       'support_data', ...
	                                         b_vname,           'data', ...
	                                         b_std_vname,       'support_data', ...
	                                         quality_vname,     'support_data', ...
	                                         pos_vg1_vname,     'data', ...
	                                         pos_vg2_vname,     'data', ...
	                                         fv_gd12_vname,     'data', ...
	                                         fv_gd21_vname,     'data', ...
	                                         recnum_vname,      'support_data', ...
	                                         recnum_gd12_vname, 'support_data', ...
	                                         recnum_gd21_vname, 'support_data', ...
	                                         q_beam_gd12_vname, 'support_data', ...
	                                         q_beam_gd21_vname, 'support_data', ...
	                                         e_labl_vname,      'metadata', ...
	                                         v_labl_vname,      'metadata', ...
	                                         d_labl_vname,      'metadata', ...
	                                         b_labl_vname,      'metadata', ...
	                                         vg_labl_vname,     'metadata' ...
	                                       }
	                                     } ...
	                  );

%------------------------------------------------------
% Write the File                                      |
%------------------------------------------------------

	spdfcdfwrite( edi_ql_file, ...
	              var_list, ...
	              'GlobalAttributes',   global_attrs, ...
	              'VariableAttributes', var_attrs,    ...
	              'VarDatatypes',       vardatatypes, ...
	              'RecordBound',        recbound      ...
	            );
end