%
% Name
%   mms_edi_write_ql_efield
%
% Purpose
%   Create a MATLAB save file of inputs needed for Bestarg.
%
% Calling Sequence
%   EDI_QL_FILE = mms_edi_write_ql_efield(EDI_QL)
%     Write EDI quick-look data constained in the structure EDI_QL
%     and created by mms_edi_create_ql_efield.m to a CDF file named
%     EDI_QL_FILE.
%
% Parameters
%   EDI_QL:         in, required, type=string
%
% Returns
%   EDI_QL_FILE     out, required, type=string
%
% MATLAB release(s) MATLAB 7.14.0.739 (R2012a)
% Required Products None
%
% History:
%   2015-06-20      Written by Matthew Argall
%   2015-07-20      Updated to v0.1.4. Corrected sign of E, added Quality, fixed
%                     attributes. Renamed from mms_sdc_edi_write_ql_efield to
%                     mms_edi_write_ql_efield - MRA
%   2015-08-19      Incorporate E-field from cost function method. Change input
%                     scheme. - MRA
%
function edi_ql_file = mms_edi_write_ql_efield(meta, beam, efield_cf, efield_bc, b_interp)
%------------------------------------%
% Create CDF File                    %
%------------------------------------%
	% Extract for ease of use
	sc      = meta.sc;
	instr   = meta.instr;
	mode    = meta.mode;
	level   = 'ql';
	optdesc = meta.optdesc;
	tstart  = meta.tstart;

	%
	% Check sizes
	%
	
	% Beam data
	assert( isa(beam.tt2000_gd12,  'int64'),  'beam.tt2000_gd12 should be int64.');
	assert( isa(beam.tt2000_gd21,  'int64'),  'beam.tt2000_gd21 should be int64.');
	assert( isa(beam.pos_vg1_dmpa, 'single'), 'beam.pos_vg1_dmpa should be single.');
	assert( isa(beam.pos_vg2_dmpa, 'single'), 'beam.pos_vg2_dmpa should be single.');
	assert( isa(beam.fv_gd12_dmpa, 'single'), 'beam.fv_gd12_dmpa should be single.');
	assert( isa(beam.fv_gd21_dmpa, 'single'), 'beam.fv_gd21_dmpa should be single.');
	assert( isa(beam.quality_gd12, 'uint8'),  'beam.quality_gd12 should be uint8.');
	assert( isa(beam.quality_gd21, 'uint8'),  'beam.quality_gd21 should be uint8.');
	
	% Beam convergence
	assert( isa(efield_bc.tt2000, 'int64'),  'efield_bc.tt2000 should be int64.' );
	assert( isa(efield_bc.E,      'single'), 'efield_bc.E should be single.');
	assert( isa(efield_bc.v_ExB,  'single'), 'efield_bc.v_ExB should be single.');
	assert( isa(efield_bc.d,      'single'), 'efield_bc.d should be single.');
	assert( isa(efield_bc.d_std,  'single'), 'efield_bc.d_std should be single.');
	assert( isa(efield_bc.quality,'uint8'),  'efield_bc.quality should be uint8.');
	
	% Cost function
	assert( isa(efield_cf.tt2000,  'int64'),  'efield_cf.tt2000 should be int64.' );
	assert( isa(efield_cf.E,       'single'), 'efield_cf.E should be single.');
	assert( isa(efield_cf.v_ExB,   'single'), 'efield_cf.v_ExB should be single.');
	assert( isa(efield_cf.d,       'single'), 'efield_cf.d should be single.');
	assert( isa(efield_cf.d_delta, 'single'), 'efield_cf.d_delta should be single.');
	
	% Interpolated B-field
	assert( isa(b_interp.b_avg,       'single'), 'b_interp.b_avg should be single.');
	assert( isa(b_interp.b_std,       'single'), 'b_interp.b_std should be single.');
	assert( isa(b_interp.recnum,      'uint32'), 'b_interp.recnum should be uint32.');
	assert( isa(b_interp.recnum_gd12, 'uint32'), 'b_interp.recnum_gd12 should be uint32.');
	assert( isa(b_interp.recnum_gd21, 'uint32'), 'b_interp.recnum_gd21 should be uint32.');

	% convert the start time to yyyy-mm-dd
	tstart = MrTimeParser(tstart, '%Y-%M-%dT%H:%m:%S', '%Y%M%d');
	                                  
	% Describe the modifications to each version
	version = 'v0.2.1';
	mods    = {  'v0.0.0 -- First version.', ...
	             'v0.0.1 -- Added gun positions.', ...
	             'v0.0.2 -- Include points with beams from single gun.', ...
	             'v0.1.0 -- Add weighting factor to beam convergence.', ...
	            ['v0.1.1 -- Added delta_plus and delta_minus variables. ' ...
	                        '0-based indices. Drift step has correct units.'], ...
	            ['v0.1.2 -- Added "recnum" variables.'], ...
	            ['v0.1.3 -- Update calculations of delta_d, v_ExB, and E.'], ...
	            ['v0.1.4 -- Corrected sign of E. Added quality. ' ... 
	                        'VAR_TYPE and "Generated_by" attributes fixed.'], ...
	            ['v0.1.5 -- v_ExB given in km/s instead of m/s. ' ...
	                        'Combine slow & fast survey. ' ...
	                        'Metadata ok by SKTEditor.'], ...
	             'v0.2.0 -- Incorporate cost function (bestarg) method.' ...
	             'v0.2.1 -- Stream lined BC and CF methods to work in tandem.' ...
	          };

	% Create the output filename
	edi_ql_file = mms_construct_filename(sc, instr, mode, level,      ...
	                                     'Directory', meta.directory, ...
	                                     'OptDesc',   optdesc,        ...
	                                     'TStart',    tstart,         ...
	                                     'Version',   version);

%------------------------------------------------------
% Global Attributes                                   |
%------------------------------------------------------
	if isempty(optdesc)
		data_type      = [mode '_' level];
		logical_source = [instr '_' mode '_' level];
	else
		data_type      = [mode '_' level '_' optdesc];
		logical_source = [instr '_' mode '_' level '_' optdesc];
	end
	[~, logical_file_id, ext] = fileparts(edi_ql_file);
	source_name = ['MMS' sc(4) '>MMS Satellite Number ' sc(4)];

	%   - Instrument Type (1+)
	%           Electric Fields (space)
	%           Magnetic Fields (space)
	%           Particles (space)
	%           Plasma and Solar Wind
	%           Spacecraft Potential Control
	global_attrs = struct( 'Data_type',                  data_type, ...
	                       'Data_version',               version, ...
	                       'Descriptor',                 'EDI', ...
	                       'Discipline',                 'Space Physics>Magnetospheric Science', ...
	                       'File_naming_convention',     'source_descriptor_datatype_yyyyMMdd', ...
	                       'Generation_date',            datestr(now(), 'yyyymmdd'), ...
	                       'Instrument_type',            'Magnetic Fields (space)', ...
	                       'Logical_file_id',            logical_file_id, ...
	                       'Logical_source',             logical_source, ...
	                       'Logical_source_description', ' ', ...
	                       'Mission_group',              'MMS', ...
	                       'PI_affiliation',             'SWRI, UNH', ...
	                       'PI_name',                    'J. Burch, R. Torbert', ...
	                       'Project',                    'STP>Solar Terrestrial Physics', ...
	                       'Source_name',                source_name, ...
	                       'TEXT',                       ['EDI electric field data. ' ...
	                                                      'Instrument papers for EDI can be found at: ' ...
	                                                      ''], ...
	                       'HTTP_LINK',                  { {'http://mms-fields.unh.edu/' ...
	                                                        'http://mms.gsfc.nasa.gov/index.html'} }, ...
	                       'LINK_TEXT',                  { {'UNH FIELDS Home Page', ...
	                                                        'NASA MMS Home'} }, ...
	                       'MODS',                       { mods }, ...
	                       'Acknowledgements',           ' ', ...
	                       'Generated_by',               'UNH', ...
	                       'Parents',                    { meta.parents }, ...
	                       'Skeleton_version',           ' ', ...
	                       'Rules_of_use',               ' ', ...
	                       'Time_resolution',            ' '  ...
	                     );

%------------------------------------------------------
% Variables                                           |
%------------------------------------------------------
	% Variable naming convention
	%   scId_instrumentId_paramName_optionalDescriptor
	
	% Cost Function Results
	tt2000_vname  = 'Epoch';
	dtt2000_vname = 'Epoch_delta_plus';
	e_cf_vname    = mms_construct_varname(sc, instr, 'E', 'dmpa');
	v_cf_vname    = mms_construct_varname(sc, instr, 'v', 'ExB_dmpa');
	d_cf_vname    = mms_construct_varname(sc, instr, 'd', 'dmpa');
	
	% Beam Convergence Results
	e_bc_vname     = mms_construct_varname(sc, instr, 'E',       'bc_dmpa'     );
	v_bc_vname     = mms_construct_varname(sc, instr, 'v',       'ExB_bc_dmpa' );
	d_bc_vname     = mms_construct_varname(sc, instr, 'd',       'bc_dmpa'     );
	d_std_bc_vname = mms_construct_varname(sc, instr, 'd',       'std_bc_dmpa' );
	q_bc_vname     = mms_construct_varname(sc, instr, 'quality', 'bc'         );
	
	% Interpolated B-field
	b_vname           = mms_construct_varname(sc, instr, 'B',      'dmpa'     );
	b_std_vname       = mms_construct_varname(sc, instr, 'B',      'std_dmpa' );
	recnum_vname      = mms_construct_varname(sc, instr, 'recnum'             );
	recnum_gd12_vname = mms_construct_varname(sc, instr, 'recnum', 'gd12'     );
	recnum_gd21_vname = mms_construct_varname(sc, instr, 'recnum', 'gd21'     );
	
	% Beam Data
	t_gd12_vname      = 'epoch_gd12_beam';
	t_gd21_vname      = 'epoch_gd21_beam';
	pos_vg1_vname     = mms_construct_varname(sc, instr, 'pos',          'virtual_gun1_dmpa');
	pos_vg2_vname     = mms_construct_varname(sc, instr, 'pos',          'virtual_gun2_dmpa');
	fv_gd12_vname     = mms_construct_varname(sc, instr, 'fv',           'gd12_dmpa');
	fv_gd21_vname     = mms_construct_varname(sc, instr, 'fv',           'gd21_dmpa');
	q_beam_gd12_vname = mms_construct_varname(sc, instr, 'beam_quality', 'gd12');
	q_beam_gd21_vname = mms_construct_varname(sc, instr, 'beam_quality', 'gd21');
	
	% Axis labels
	e_labl_vname     = 'E_Labl_Ptr';
	v_labl_vname     = 'v_Labl_Ptr';
	d_labl_vname     = 'd_Labl_Ptr';
	b_labl_vname     = 'B_Labl_Ptr';
	b_std_labl_vname = 'B_std_Labl_Ptr';
	d_std_labl_vname = 'd_std_Labl_Ptr';
	fv_labl_vname    = 'fv_Labl_Ptr';
	vg_labl_vname    = 'vg_Labl_Ptr';

	% Variable Data
	var_list = { tt2000_vname,       efield_cf.tt2000',     ...
	             dtt2000_vname,      b_interp.dt_avg,          ...
	             e_cf_vname,         efield_cf.E',     ...
	             v_cf_vname,         efield_cf.v_ExB',     ...
	             d_cf_vname,         efield_cf.d',     ...
	             e_bc_vname,         efield_bc.E',     ...
	             v_bc_vname,         efield_bc.v_ExB',     ...
	             d_bc_vname,         efield_bc.d',     ...
	             d_std_bc_vname,     efield_bc.d_std', ...
	             q_bc_vname,         efield_bc.quality',    ...
	             b_vname,            b_interp.b_avg',          ...
	             b_std_vname,        b_interp.b_std',          ...
	             recnum_vname,       b_interp.recnum',         ...
	             recnum_gd12_vname,  b_interp.recnum_gd12',    ...
	             recnum_gd21_vname,  b_interp.recnum_gd21',    ...
	             t_gd12_vname,       beam.tt2000_gd12',        ...
	             t_gd21_vname,       beam.tt2000_gd21',        ...
	             pos_vg1_vname,      beam.pos_vg1_dmpa',       ...
	             pos_vg2_vname,      beam.pos_vg2_dmpa',       ...
	             fv_gd12_vname,      beam.fv_gd12_dmpa',       ...
	             fv_gd21_vname,      beam.fv_gd21_dmpa',       ...
	             q_beam_gd12_vname,  beam.quality_gd12',       ...
	             q_beam_gd21_vname,  beam.quality_gd21',       ...
	             e_labl_vname,       { 'Ex'  'Ey'  'Ez'},      ...
	             v_labl_vname,       { 'vx'  'vy'  'vz'},      ...
	             d_labl_vname,       {  'x'   'y'   'z'},      ...
	             b_labl_vname,       { 'Bx'  'By'  'Bz'},      ...
	             d_std_labl_vname,   { 'dx'  'dy'  'dz'},      ...
	             b_std_labl_vname,   {'dBx' 'dBy' 'dBz'},      ...
	             fv_labl_vname,      {'FVx' 'FVy' 'FVz'},      ...
	             vg_labl_vname,      {  'x'   'y'   'z'}       ...
	           };

	% Record Variance
	recbound = { tt2000_vname,      ...
	             e_cf_vname,        ...
	             v_cf_vname,        ...
	             d_cf_vname,        ...
	             e_bc_vname,        ...
	             v_bc_vname,        ...
	             d_bc_vname,        ...
	             d_std_bc_vname,    ...
	             q_bc_vname,        ...
	             b_vname,           ...
	             b_std_vname,       ...
	             recnum_vname,      ...
	             recnum_gd12_vname, ...
	             recnum_gd21_vname, ...
	             t_gd12_vname,      ...
	             t_gd21_vname,      ...
	             pos_vg1_vname,     ...
	             pos_vg2_vname,     ...
	             fv_gd12_vname,     ...
	             fv_gd21_vname,     ...
	             q_beam_gd12_vname, ...
	             q_beam_gd21_vname, ...
	           };

	% Data types
	vardatatypes = { tt2000_vname,       'cdf_time_tt2000', ...
	                 dtt2000_vname,      'cdf_time_tt2000', ...
	                 e_cf_vname,         'cdf_float',       ...
	                 v_cf_vname,         'cdf_float',       ...
	                 d_cf_vname,         'cdf_float',       ...
	                 e_bc_vname,         'cdf_float',       ...
	                 v_bc_vname,         'cdf_float',       ...
	                 d_bc_vname,         'cdf_float',       ...
	                 d_std_bc_vname,     'cdf_float',       ...
	                 q_bc_vname,         'cdf_uint1',       ...
	                 b_vname,            'cdf_float',       ...
	                 b_std_vname,        'cdf_float',       ...
	                 recnum_vname,       'cdf_uint4',       ...
	                 recnum_gd12_vname,  'cdf_uint4',       ...
	                 recnum_gd21_vname,  'cdf_uint4',       ...
	                 t_gd12_vname,       'cdf_time_tt2000', ...
	                 t_gd21_vname,       'cdf_time_tt2000', ...
	                 pos_vg1_vname,      'cdf_float',       ...
	                 pos_vg2_vname,      'cdf_float',       ...
	                 fv_gd12_vname,      'cdf_float',       ...
	                 fv_gd21_vname,      'cdf_float',       ...
	                 q_beam_gd12_vname,  'cdf_uint1',       ...
	                 q_beam_gd21_vname,  'cdf_uint1',       ...
	                 e_labl_vname,       'cdf_char',        ...
	                 v_labl_vname,       'cdf_char',        ...
	                 d_labl_vname,       'cdf_char',        ...
	                 b_labl_vname,       'cdf_char',        ...
	                 d_std_labl_vname,   'cdf_char',        ...
	                 b_std_labl_vname,   'cdf_char',        ...
	                 fv_labl_vname,      'cdf_char',        ...
	                 vg_labl_vname,      'cdf_char'         ...
	               };
	

%------------------------------------------------------
% Variable Attributes                                 |
%------------------------------------------------------
	%
	% This assignment fails because the cell arrays do not have the same
	% number of elements. Adding variable attributes will have to be done
	% with cdflib.
	%
	var_attrs = struct( ...
		'CATDESC',     { ...
		                  { tt2000_vname,  'TT2000 time tags for EDI electric field data.', ...
		                    dtt2000_vname, 'Upper bound for the time stamps.', ...
		                    e_cf_vname,    ['Electric field computed via the "bestarg" method. ' ...
		                                    'It is derived from the drift step, vector magnetic '...
		                                    'field, and gyroperiod.'], ...
		                    v_cf_vname,    ['ExB drift velocity computed via the "bestarg" method. ' ...
		                                    'It is derived the drift step and gyroperiods.'], ...
		                    d_cf_vname,    ['Drift step (distance an electron drifts in one gyro-period) ' ...
		                                    'derived from EDI beam data via "bestarg" method. ' ... 
		                                    'The implementation is such that EDI firing directions ' ...
		                                    'in BPP are compared against the angle from each gun to ' ...
		                                    'each target in a grid of potential targets. The grid ' ...
		                                    'point with the smallest associated deviation is selected ' ...
		                                    'as the virtual source point.'], ...
		                    e_bc_vname,    ['Electric field computed via the "beam convergence" method. ' ...
		                                    'It is derived from the drift step, vector magnetic '...
		                                    'field, and gyroperiod.'], ...
		                    v_bc_vname,    ['ExB drift velocity computed via the "beam convergence" method. ' ...
		                                    'It is derived the drift step and gyroperiods.'], ...
		                    d_bc_vname,    ['Drift step (distance an electron drifts in one gyro-period) ' ...
		                                    'derived from EDI beam data via "beam convergence" method. ' ... 
		                                    'The implementation is such that virtual source point is ' ...
		                                    'taken to be the centroid of weighted EDI beam intersections.'], ...
		                    d_std_bc_vname, 'Standard deviation of the beam convergence drift step.', ...
		                    q_bc_vname,     'Quality flag for beam convergence data.', ...
		                    b_vname,      ['5-second averaged magnetic field data used to define ' ...
		                                   'the plane perpendicular to B, in which the bestarg ' ...
		                                   'and beam convergence methods are executed.'], ...
		                    b_std_vname,   'Standard deviation of the averaged magnetic field.', ...
		                    recnum_vname,      ['Record number of each element of all bestarg, beam convergence, ' ...
		                                        'and averaged magnetic field data. Used to cross-reference the ' ...
		                                        'beam information used in computing such data.'], ...
		                    recnum_gd12_vname, ['Each beam from Gun1 is given a record number that references ' ...
		                                        'the E-field record for which it was used.'], ...
		                    recnum_gd21_vname, ['Each beam from Gun2 is given a record number that references ' ...
		                                        'the E-field record for which it was used.'], ...
		                    t_gd12_vname,      'TT2000 time tags for EDI GDU1 beam data.', ...
		                    t_gd21_vname,      'TT2000 time tags for EDI GDU2 beam data.', ...
		                    pos_vg1_vname,     'Position of gun1 on the virtual spacecraft.', ...
		                    pos_vg2_vname,     'Position of gun2 on the virtual spacecraft.', ...
		                    fv_gd12_vname,     'Firing vectors from the gun1-detector2 pair, in DMPA coordinates.', ...
		                    fv_gd21_vname,     'Firing vectors from the gun2-detector1 pair, in DMPA coordinates.', ...
		                    q_beam_gd12_vname, 'The quality of GD12 beams used to find the drift step.', ...
		                    q_beam_gd21_vname, 'The quality of GD21 beams used to find the drift step.', ...
		                    e_labl_vname,      'Axis labels for electric field', ...
		                    v_labl_vname,      'Axis labels for drift velocity', ...
		                    d_labl_vname,      'Axis labels for drift step.', ...
		                    b_labl_vname,      'Axis labels for magnetic field.', ...
		                    d_std_labl_vname,  'Axis labels for the standard deviation of the drift step.', ...
		                    b_std_labl_vname,  'Axis labels for the standard deviation of the magnetic field.', ...
		                    fv_labl_vname,     'Axis labels for the firing vector directions.', ...
		                    vg_labl_vname,     'Axis labels for virtual gun positions.' ...
		                  } ...
		                }, ...
		'DEPEND_0',    {  ...
		                  { e_cf_vname,        tt2000_vname, ...
		                    v_cf_vname,        tt2000_vname, ...
		                    d_cf_vname,        tt2000_vname, ...
		                    e_bc_vname,        tt2000_vname, ...
		                    v_bc_vname,        tt2000_vname, ...
		                    d_bc_vname,        tt2000_vname, ...
		                    d_std_bc_vname,    tt2000_vname, ...
		                    q_bc_vname,        tt2000_vname, ...
		                    b_vname,           tt2000_vname, ...
		                    b_std_vname,       tt2000_vname, ...
		                    recnum_vname,      tt2000_vname, ...
		                    recnum_gd12_vname, t_gd12_vname, ...
		                    recnum_gd21_vname, t_gd21_vname, ...
		                    pos_vg1_vname,     t_gd12_vname, ...
		                    pos_vg2_vname,     t_gd21_vname, ...
		                    fv_gd12_vname,     t_gd12_vname, ...
		                    fv_gd21_vname,     t_gd21_vname, ...
		                    q_beam_gd12_vname, t_gd12_vname, ...
		                    q_beam_gd21_vname, t_gd21_vname ...
		                  } ...
		               }, ...
		'DELTA_PLUS_VAR', {  ...
		                  { tt2000_vname, dtt2000_vname,  ...
		                    d_bc_vname,   d_std_bc_vname, ...
		                    b_vname,      b_std_vname     ...
		                  } ...
		               }, ...
		'DELTA_MINUS_VAR', {  ...
		                  { d_bc_vname,   d_std_bc_vname, ...
		                    b_vname,      b_std_vname     ...
		                  } ...
		               }, ...
		'DISPLAY_TYPE',{  ... 
		                  { e_cf_vname,        'time_series', ...
		                    v_cf_vname,        'time_series', ...
		                    d_cf_vname,        'time_series', ...
		                    e_bc_vname,        'time_series', ...
		                    v_bc_vname,        'time_series', ...
		                    d_bc_vname,        'time_series', ...
		                    b_vname,           'time_series', ...
		                    pos_vg1_vname,     'time_series', ...
		                    pos_vg2_vname,     'time_series', ...
		                    fv_gd12_vname,     'time_series', ...
		                    fv_gd21_vname,     'time_series'  ...
		                  } ...
		               }, ...
		 'FIELDNAM',      {  ...
		                    { tt2000_vname,      'Time',               ...
		                      dtt2000_vname,     'dt',                 ...
		                      e_cf_vname,        'Electric Field',     ...
		                      v_cf_vname,        'ExB Drift Velocity', ...
		                      d_cf_vname,        'Drift Step',         ...
		                      e_bc_vname,        'Electric Field',     ...
		                      v_bc_vname,        'ExB Drift Velocity', ...
		                      d_bc_vname,        'Drift Step',         ...
		                      d_std_bc_vname,    'delta d',            ...
		                      q_bc_vname,        'Quality',            ...
		                      b_vname,           'Magnetic Field',     ...
		                      b_std_vname,       'delta B',            ...
		                      recnum_vname,      'Record',             ...
		                      recnum_gd12_vname, 'Record',             ...
		                      recnum_gd21_vname, 'Record',             ...
		                      t_gd12_vname,      'Time',               ...
		                      t_gd21_vname,      'Time',               ...
		                      pos_vg1_vname,     'Gun Position',       ...
		                      pos_vg2_vname,     'Gun Position',       ...
		                      fv_gd12_vname,     'Firing vectors',     ...
		                      fv_gd21_vname,     'Firing vectors',     ...
		                      q_beam_gd12_vname, 'GD12 beam quality',  ...
		                      q_beam_gd21_vname, 'GD21 beam quality',  ...
		                      e_labl_vname,      'Axis Labels',        ...
		                      v_labl_vname,      'Axis Labels',        ...
		                      d_labl_vname,      'Axis Labels',        ...
		                      b_labl_vname,      'Axis Labels',        ...
		                      d_std_labl_vname,  'Axis Labels',        ...
		                      b_std_labl_vname,  'Axis Labels',        ...
		                      fv_labl_vname,     'Axis Labels',        ...
		                      vg_labl_vname,     'Axis Labels'         ...
		                    }
		                  }, ...
		 'FILLVAL',       {  ...
		                    { tt2000_vname,      spdfcomputett2000([9999 12 31 23 59 59 999 999 999]), ...
		                      dtt2000_vname,     spdfcomputett2000([9999 12 31 23 59 59 999 999 999]), ...
		                      t_gd12_vname,      spdfcomputett2000([9999 12 31 23 59 59 999 999 999]), ...
		                      t_gd21_vname,      spdfcomputett2000([9999 12 31 23 59 59 999 999 999]), ...
		                      e_cf_vname,        single(-1.0E31),    ...
		                      v_cf_vname,        single(-1.0E31),    ...
		                      d_cf_vname,        single(-1.0E31),    ...
		                      e_bc_vname,        single(-1.0E31),    ...
		                      v_bc_vname,        single(-1.0E31),    ...
		                      d_bc_vname,        single(-1.0E31),    ...
		                      d_std_bc_vname,    single(-1.0E31),    ...
		                      q_bc_vname,        uint8(255),         ...
		                      b_vname,           single(-1.0E31),    ...
		                      b_std_vname,       single(-1.0E31),    ...
		                      recnum_vname,      uint32(4294967295), ...
		                      recnum_gd12_vname, uint32(4294967295), ...
		                      recnum_gd21_vname, uint32(4294967295), ...
		                      pos_vg1_vname,     single(-1.0E31),    ...
		                      pos_vg2_vname,     single(-1.0E31),    ...
		                      fv_gd12_vname,     single(-1.0E31),    ...
		                      fv_gd21_vname,     single(-1.0E31),    ...
		                      q_beam_gd12_vname, uint8(255),         ...
		                      q_beam_gd21_vname, uint8(255),         ...
		                    } ...
		                  }, ...
		 'FORMAT',        {  ...
		                    { tt2000_vname,      'I16',   ...
		                      dtt2000_vname,     'I16',   ...
		                      e_cf_vname,        'F14.6', ...
		                      v_cf_vname,        'F14.6', ...
		                      d_cf_vname,        'F14.6', ...
		                      e_bc_vname,        'F14.6', ...
		                      v_bc_vname,        'F14.6', ...
		                      d_bc_vname,        'F14.6', ...
		                      d_std_bc_vname,    'F14.6', ...
		                      q_bc_vname,        'I1',    ...
		                      b_vname,           'F14.6', ...
		                      b_std_vname,       'F14.6', ...
		                      recnum_vname,      'I10',   ...
		                      recnum_gd12_vname, 'I10',   ...
		                      recnum_gd21_vname, 'I10',   ...
		                      t_gd12_vname,      'I16',   ...
		                      t_gd21_vname,      'I16',   ...
		                      pos_vg1_vname,     'F14.6', ...
		                      pos_vg2_vname,     'F14.6', ...
		                      fv_gd12_vname,     'F14.6', ...
		                      fv_gd21_vname,     'F14.6', ...
		                      q_beam_gd12_vname, 'I1',    ...
		                      q_beam_gd21_vname, 'I1',    ...
		                      e_labl_vname,      'A2',    ...
		                      v_labl_vname,      'A2',    ...
		                      d_labl_vname,      'A2',    ...
		                      b_labl_vname,      'A2',    ...
		                      d_std_labl_vname,  'A2',    ...
		                      b_std_labl_vname,  'A3',    ...
		                      fv_labl_vname,     'A3',    ...
		                      vg_labl_vname,     'A1'     ...
		                    } ...
		                  }, ...
		 'LABLAXIS',      {  ...
		                    { tt2000_vname,      'UT',...
		                      t_gd12_vname,      'UT',...
		                      t_gd21_vname,      'UT',...
		                      q_bc_vname,        'Quality', ...
		                      recnum_vname,      'Record', ...
		                      recnum_gd12_vname, 'Record', ...
		                      recnum_gd21_vname, 'Record', ...
		                      q_beam_gd12_vname, 'Quality', ...
		                      q_beam_gd21_vname, 'Quality' ...
		                    } ...
		                  }, ...
		 'LABL_PTR_1',    {  ...
		                    { e_cf_vname,     e_labl_vname,     ...
		                      v_cf_vname,     v_labl_vname,     ...
		                      d_cf_vname,     d_labl_vname,     ...
		                      e_bc_vname,     e_labl_vname,     ...
		                      v_bc_vname,     v_labl_vname,     ...
		                      d_bc_vname,     d_labl_vname,     ...
		                      d_std_bc_vname, d_std_labl_vname, ...
		                      b_vname,        b_labl_vname,     ...
		                      b_std_vname,    b_std_labl_vname, ...
		                      pos_vg1_vname,  vg_labl_vname,    ...
		                      pos_vg2_vname,  vg_labl_vname,    ...
		                      fv_gd12_vname,  fv_labl_vname,    ...
		                      fv_gd21_vname,  fv_labl_vname     ...
		                    } ...
		                  }, ...
		 'SI_CONVERSION', {  ...
		                  { tt2000_vname,   '1e-9>seconds',      ...
		                    dtt2000_vname,  '1e-9>seconds',      ...
		                    e_cf_vname,     '1e-3>Volts/meter',  ...
		                    v_cf_vname,     '1e3>meters/second', ...
		                    d_cf_vname,     '1e0>meters',        ...
		                    e_bc_vname,     '1e-3>Volts/meter',  ...
		                    v_bc_vname,     '1e3>meters/second', ...
		                    d_bc_vname,     '1e0>meters',        ...
		                    d_std_bc_vname, '1e0>meters',        ...
		                    b_vname,        '1e-9>Tesla',        ...
		                    b_std_vname,    '1e-9>Tesla',        ...
		                    t_gd12_vname,   '1e-9>seconds',      ...
		                    t_gd21_vname,   '1e-9>seconds',      ...
		                    pos_vg1_vname,  '1e0>meters',        ...
		                    pos_vg2_vname,  '1e0>meters'         ...
		                  } ...
		               }, ...
		 'TIME_BASE',  {  ...
		                  { tt2000_vname,  'J2000', ...
		                    t_gd12_vname,  'J2000', ...
		                    t_gd21_vname,  'J2000', ...
		                  } ...
		               }, ...
		 'UNITS',      {  ...
		                  { tt2000_vname,   'ns',   ...
		                    dtt2000_vname,  'ns',   ...
		                    t_gd12_vname,   'ns',   ...
		                    t_gd21_vname,   'ns',   ...
		                    e_cf_vname,     'mV/m', ...
		                    v_cf_vname,     'km/s', ...
		                    d_cf_vname,     'm',    ...
		                    e_bc_vname,     'mV/m', ...
		                    v_bc_vname,     'km/s', ...
		                    d_bc_vname,     'm',    ...
		                    d_std_bc_vname, 'm',    ...
		                    b_vname,        'nT',   ...
		                    b_std_vname,    'nT',   ...
		                    pos_vg1_vname,  'm',    ...
		                    pos_vg2_vname,  'm',    ...
		                  } ...
		               }, ...
		 'VALIDMIN',   {  ...
		                  { tt2000_vname,      spdfcomputett2000([2015 3 1 0 0 0 0 0 0]), ...
		                    dtt2000_vname,     int64(0),          ...
		                    e_cf_vname,        single(-100000.0), ...
		                    v_cf_vname,        single(-100000.0), ...
		                    d_cf_vname,        single(-100000.0), ...
		                    e_bc_vname,        single(-100000.0), ...
		                    v_bc_vname,        single(-100000.0), ...
		                    d_bc_vname,        single(-100000.0), ...
		                    d_std_bc_vname,    single(-1000.0),   ...
		                    q_bc_vname,        uint8(0),          ...
		                    b_vname,           single(-100000.0), ...
		                    b_std_vname,       single(-1000.0),   ...
		                    recnum_vname,      int32(0),          ...
		                    recnum_gd12_vname, int32(0),          ...
		                    recnum_gd21_vname, int32(0),          ...
		                    t_gd12_vname,      spdfcomputett2000([2015 3 1 0 0 0 0 0 0]), ...
		                    t_gd21_vname,      spdfcomputett2000([2015 3 1 0 0 0 0 0 0]), ...
		                    pos_vg1_vname,     single(-20),       ...
		                    pos_vg2_vname,     single(-20),       ...
		                    fv_gd12_vname,     single(-100000.0), ...
		                    fv_gd21_vname,     single(-100000.0), ...
		                    q_beam_gd12_vname, int8(0),           ...
		                    q_beam_gd21_vname, int8(0)            ...
		                  }
		               }, ...
		 'VALIDMAX',   {  ...
		                  { tt2000_vname,      spdfcomputett2000([2050 3 1 0 0 0 0 0 0]), ...
		                    dtt2000_vname,     int64(2e10),       ...
		                    e_cf_vname,        single(100000.0),  ...
		                    v_cf_vname,        single(100000.0),  ...
		                    d_cf_vname,        single(100000.0),  ...
		                    e_bc_vname,        single(100000.0),  ...
		                    v_bc_vname,        single(100000.0),  ...
		                    d_bc_vname,        single(100000.0),  ...
		                    d_std_bc_vname,    single(1000.0),    ...
		                    q_bc_vname,        uint8(3),          ...
		                    b_vname,           single(100000.0),  ...
		                    b_std_vname,       single(1000.0),    ...
		                    recnum_vname,      int32(4294967295), ...
		                    recnum_gd12_vname, int32(4294967295), ...
		                    recnum_gd21_vname, int32(4294967295), ...
		                    t_gd12_vname,      spdfcomputett2000([2050 3 1 0 0 0 0 0 0]), ...
		                    t_gd21_vname,      spdfcomputett2000([2050 3 1 0 0 0 0 0 0]), ...
		                    pos_vg1_vname,     single(20),        ...
		                    pos_vg2_vname,     single(20),        ...
		                    fv_gd12_vname,     single(100000.0),  ...
		                    fv_gd21_vname,     single(100000.0),  ...
		                    q_beam_gd12_vname, int8(3),           ...
		                    q_beam_gd21_vname, int8(3)            ...
		                  }
		               }, ...
		 'VAR_TYPE',   {  ...
		                  { tt2000_vname,      'support_data', ...
		                    dtt2000_vname,     'support_data', ...
		                    e_cf_vname,        'data',         ...
		                    v_cf_vname,        'data',         ...
		                    d_cf_vname,        'data',         ...
		                    e_bc_vname,        'data',         ...
		                    v_bc_vname,        'data',         ...
		                    d_bc_vname,        'data',         ...
		                    d_std_bc_vname,    'support_data', ...
		                    q_bc_vname,        'support_data', ...
		                    b_vname,           'data',         ...
		                    b_std_vname,       'support_data', ...
		                    recnum_vname,      'support_data', ...
		                    recnum_gd12_vname, 'support_data', ...
		                    recnum_gd21_vname, 'support_data', ...
		                    t_gd12_vname,      'support_data', ...
		                    t_gd21_vname,      'support_data', ...
		                    pos_vg1_vname,     'data',         ...
		                    pos_vg2_vname,     'data',         ...
		                    fv_gd12_vname,     'data',         ...
		                    fv_gd21_vname,     'data',         ...
		                    q_beam_gd12_vname, 'support_data', ...
		                    q_beam_gd21_vname, 'support_data', ...
		                    e_labl_vname,      'metadata',     ...
		                    v_labl_vname,      'metadata',     ...
		                    d_labl_vname,      'metadata',     ...
		                    b_labl_vname,      'metadata',     ...
		                    d_std_labl_vname,  'metadata',     ...
		                    b_std_labl_vname,  'metadata',     ...
		                    fv_labl_vname,     'metadata',     ...
		                    vg_labl_vname,     'metadata'      ...
		                  }
		               } ...
		);

%------------------------------------------------------
% Write the File                                      |
%------------------------------------------------------
	spdfcdfwrite( edi_ql_file,                        ...
	              var_list,                           ...
	              'GlobalAttributes',   global_attrs, ...
	              'VariableAttributes', var_attrs,    ...
	              'VarDatatypes',       vardatatypes, ...
	              'RecordBound',        recbound      ...
	            );
end