%
% Name
%   mms_edi_l2_q0_write
%
% Purpose
%   Create a MATLAB save file of inputs needed for Bestarg.
%
% Calling Sequence
%   EDI_QL_FILE = mms_edi_ql_efield_write(EDI_QL)
%     Write EDI quick-look data constained in the structure EDI_QL
%     and created by mms_edi_create_ql_efield.m to a CDF file named
%     EDI_QL_FILE.
%
% Parameters
%   EDI_QL:         in, required, type=string
%
% Returns
%   EDI_QL_FILE     out, required, type=string
%
% MATLAB release(s) MATLAB 7.14.0.739 (R2012a)
% Required Products None
%
% History:
%   2015-09-10      Written by Matthew Argall
%
function q0_file = mms_edi_l2_q0_write(meta, q0_data)
%------------------------------------%
% Create CDF File                    %
%------------------------------------%
	% Extract for ease of use
	sc      = meta.sc;
	instr   = meta.instr;
	mode    = meta.mode;
	level   = 'l2';
	optdesc = meta.optdesc;
	tstart  = meta.tstart;

	%
	% Check sizes
	%
	assert( isa(q0_data.tt2000_gd12, 'int64'),  'q0_data.tt2000_gd12 should be int64.' );
	assert( isa(q0_data.tt2000_gd21, 'int64'),  'q0_data.tt2000_gd21 should be int64.');
	assert( isa(q0_data.energy_gd12, 'uint16'), 'q0_data.energy_gd12 should be uint16.');
	assert( isa(q0_data.energy_gd21, 'uint16'), 'q0_data.energy_gd21 should be uint16.');
	assert( isa(q0_data.counts_gd12, 'uint16'), 'q0_data.counts_gd12 should be uint16.');
	assert( isa(q0_data.counts_gd21, 'uint16'), 'q0_data.counts_gd21 should be uint16.');
	
	% convert the start time to yyyy-mm-dd
	tstart = MrTimeParser(tstart, '%Y-%M-%dT%H:%m:%S', '%Y%M%d');
	                                  
	% Describe the modifications to each version
	mods    = {  'v0.0.0 -- First version.' ...
	             'v0.0.1 -- Filled energy variables.' ...
	             'v0.0.2 -- Energy written properly.' ...
	          };
	version = regexp( mods{end}, '^v[0-9]+\.[0-9]+\.[0-9]+', 'match' );

	% Create the output filename
	q0_file = mms_construct_filename( sc, instr, mode, level,      ...
	                                  'Directory', meta.directory, ...
	                                  'OptDesc',   optdesc,        ...
	                                  'TStart',    tstart,         ...
	                                  'Version',   version );

%------------------------------------------------------
% Global Attributes                                   |
%------------------------------------------------------
	if isempty(optdesc)
		data_type      = [mode '_' level];
		logical_source = [instr '_' mode '_' level];
	else
		data_type      = [mode '_' level '_' optdesc];
		logical_source = [instr '_' mode '_' level '_' optdesc];
	end
	[~, logical_file_id, ext] = fileparts(q0_file);
	source_name = ['MMS' sc(4) '>MMS Satellite Number ' sc(4)];

	%   - Instrument Type (1+)
	%           Electric Fields (space)
	%           Magnetic Fields (space)
	%           Particles (space)
	%           Plasma and Solar Wind
	%           Spacecraft Potential Control
	global_attrs = struct( 'Data_type',                  data_type, ...
	                       'Data_version',               version, ...
	                       'Descriptor',                 'EDI', ...
	                       'Discipline',                 'Space Physics>Magnetospheric Science', ...
	                       'File_naming_convention',     'source_descriptor_datatype_yyyyMMdd', ...
	                       'Generation_date',            datestr(now(), 'yyyymmdd'), ...
	                       'Instrument_type',            'Magnetic Fields (space)', ...
	                       'Logical_file_id',            logical_file_id, ...
	                       'Logical_source',             logical_source, ...
	                       'Logical_source_description', 'Level 2 EDI Quality 0 Counts', ...
	                       'Mission_group',              'MMS', ...
	                       'PI_affiliation',             'SWRI, UNH', ...
	                       'PI_name',                    'J. Burch, R. Torbert', ...
	                       'Project',                    'STP>Solar Terrestrial Physics', ...
	                       'Source_name',                source_name, ...
	                       'TEXT',                       ['EDI electric field data. ' ...
	                                                      'Instrument papers for EDI can be found at: ' ...
	                                                      'http://link.springer.com/article/10.1007%2Fs11214-015-0182-7'], ...
	                       'HTTP_LINK',                  { {'http://mms-fields.unh.edu/' ...
	                                                        'http://mms.gsfc.nasa.gov/index.html'} }, ...
	                       'LINK_TEXT',                  { {'UNH FIELDS Home Page', ...
	                                                        'NASA MMS Home'} }, ...
	                       'MODS',                       { mods }, ...
	                       'Acknowledgements',           ' ', ...
	                       'Generated_by',               'UNH', ...
	                       'Parents',                    { meta.parents }, ...
	                       'Skeleton_version',           ' ', ...
	                       'Rules_of_use',               ' ', ...
	                       'Time_resolution',            ' '  ...
	                     );

%------------------------------------------------------
% Variables                                           |
%------------------------------------------------------
	% Variable naming convention
	%   scId_instrumentId_paramName_optionalDescriptor
	
	t_gd12_vname      = 'epoch_gd12';
	t_gd21_vname      = 'epoch_gd21';
	e_gd12_vname      = mms_construct_varname(sc, instr, 'energy', 'gd12');
	e_gd21_vname      = mms_construct_varname(sc, instr, 'energy', 'gd21');
	counts_gd12_vname = mms_construct_varname(sc, instr, 'counts', 'gd12');
	counts_gd21_vname = mms_construct_varname(sc, instr, 'counts', 'gd21');

	% Variable Data
	var_list = { t_gd12_vname,       q0_data.tt2000_gd12', ...
	             t_gd21_vname,       q0_data.tt2000_gd21', ...
	             e_gd12_vname,       q0_data.energy_gd12', ...
	             e_gd21_vname,       q0_data.energy_gd21', ...
	             counts_gd12_vname,  q0_data.counts_gd12', ...
	             counts_gd21_vname,  q0_data.counts_gd21'  ...
	           };

	% Record Variance
	recbound = { t_gd12_vname,      ...
	             t_gd21_vname,      ...
	             e_gd12_vname,      ...
	             e_gd21_vname,      ...
	             counts_gd12_vname, ...
	             counts_gd21_vname  ...
	           };

	% Data types
	vardatatypes = { t_gd12_vname,       'cdf_time_tt2000', ...
	                 t_gd21_vname,       'cdf_time_tt2000', ...
	                 e_gd12_vname,       'cdf_uint2',       ...
	                 e_gd21_vname,       'cdf_uint2',       ...
	                 counts_gd12_vname,  'cdf_uint2',       ...
	                 counts_gd21_vname,  'cdf_uint2'        ...
	               };
	

%------------------------------------------------------
% Variable Attributes                                 |
%------------------------------------------------------
	%
	% This assignment fails because the cell arrays do not have the same
	% number of elements. Adding variable attributes will have to be done
	% with cdflib.
	%
	% GD12 = Gun1-Detector2 pair. Counts is a detector quantity. Technically,
	% energy is a gun quantity, but since the guns and detectors are never
	% operated at different energies, we are considering them to be a detector
	% quantity for the purposes of Q0 counts detection.
	%
	var_attrs = struct( ...
		'CATDESC',     { ...
		                  { t_gd12_vname,      'TT2000 time tags for quality 0 EDI GDU2 counts.', ...
		                    t_gd21_vname,      'TT2000 time tags for quality 0 EDI GDU1 counts.', ...
		                    counts_gd12_vname, 'GDU2 quality 0 counts.', ...
		                    counts_gd21_vname, 'GDU1 quality 0 counts.', ...
		                    e_gd12_vname,      'GDU2 beam energy.', ...
		                    e_gd21_vname,      'GDU1 beam energy.' ...
		                  } ...
		                }, ...
		'DEPEND_0',    {  ...
		                  { counts_gd12_vname, t_gd12_vname, ...
		                    counts_gd21_vname, t_gd21_vname, ...
		                    e_gd12_vname,      t_gd12_vname, ...
		                    e_gd21_vname,      t_gd21_vname  ...
		                  } ...
		               }, ...
		'DISPLAY_TYPE',{  ... 
		                  { counts_gd12_vname, 'time_series', ...
		                    counts_gd21_vname, 'time_series', ...
		                    e_gd12_vname,      'time_series', ...
		                    e_gd21_vname,      'time_series'  ...
		                  } ...
		               }, ...
		'FIELDNAM',    {  ...
		                  { t_gd12_vname,      'Time',             ...
		                    t_gd21_vname,      'Time',             ...
		                    counts_gd12_vname, 'Quality 0 Counts', ...
		                    counts_gd21_vname, 'Quality 0 Counts', ...
		                    e_gd12_vname,      'Energy', ...
		                    e_gd21_vname,      'Energy'  ...
		                  }
		               }, ...
		 'FILLVAL',    {  ...
		                  { t_gd12_vname,      spdfcomputett2000([9999 12 31 23 59 59 999 999 999]), ...
		                    t_gd21_vname,      spdfcomputett2000([9999 12 31 23 59 59 999 999 999]), ...
		                    counts_gd12_vname, uint16(65535), ...
		                    counts_gd21_vname, uint16(65535), ...
		                    e_gd12_vname,      uint16(65535), ...
		                    e_gd21_vname,      uint16(65535)  ...
		                  } ...
		               }, ...
		'FORMAT',      {  ...
		                  { t_gd12_vname,      'I16', ...
		                    t_gd21_vname,      'I16', ...
		                    counts_gd12_vname, 'I5',  ...
		                    counts_gd21_vname, 'I5',  ...
		                    e_gd12_vname,      'I5',  ...
		                    e_gd21_vname,      'I5'   ...
		                  } ...
		               }, ...
		'LABLAXIS',    {  ...
		                  { t_gd12_vname,      'UT',        ...
		                    t_gd21_vname,      'UT',        ...
		                    counts_gd12_vname, 'Q0 Counts', ...
		                    counts_gd21_vname, 'Q0 Counts', ...
		                    e_gd12_vname,      'Energy',    ...
		                    e_gd21_vname,      'Energy'     ...
		                  } ...
		                }, ...
		'SI_CONVERSION',{  ...
		                  { t_gd12_vname,   '1e-9>s',   ...
		                    t_gd21_vname,   '1e-9>s'    ...
		                  } ...
		               }, ...
		'TIME_BASE', {  ...
		                { t_gd12_vname,  'J2000', ...
		                  t_gd21_vname,  'J2000', ...
		                } ...
		             }, ...
		'UNITS',     {  ...
		                { t_gd12_vname,      'ns',     ...
		                  t_gd21_vname,      'ns',     ...
		                  counts_gd12_vname, 'counts', ...
		                  counts_gd21_vname, 'counts', ...
		                  e_gd12_vname,      'eV',     ...
		                  e_gd21_vname,      'eV'      ...
		                } ...
		             }, ...
		'VALIDMIN',  {  ...
		                { t_gd12_vname,      spdfcomputett2000([2015 3 1 0 0 0 0 0 0]), ...
		                  t_gd21_vname,      spdfcomputett2000([2015 3 1 0 0 0 0 0 0]), ...
		                  counts_gd12_vname, uint16(0), ...
		                  counts_gd21_vname, uint16(0), ...
		                  e_gd12_vname,      uint16(0), ...
		                  e_gd21_vname,      uint16(0)  ...
		                }
		             }, ...
		'VALIDMAX',  {  ...
		                { t_gd12_vname,      spdfcomputett2000([2050 3 1 0 0 0 0 0 0]), ...
		                  t_gd21_vname,      spdfcomputett2000([2050 3 1 0 0 0 0 0 0]), ...
		                  counts_gd12_vname, uint16(65534), ...
		                  counts_gd21_vname, uint16(65534), ...
		                  e_gd12_vname,      uint16(1000),  ...
		                  e_gd21_vname,      uint16(1000)   ...
		                }
		             }, ...
		'VAR_TYPE',  {  ...
		                { t_gd12_vname,      'support_data', ...
		                  t_gd21_vname,      'support_data'  ...
		                  counts_gd12_vname, 'data',         ...
		                  counts_gd21_vname, 'data',         ...
		                  e_gd12_vname,      'support_data', ...
		                  e_gd21_vname,      'support_data'  ...
		                }
		             } ...
		);

%------------------------------------------------------
% Write the File                                      |
%------------------------------------------------------
	spdfcdfwrite( q0_file,                            ...
	              var_list,                           ...
	              'GlobalAttributes',   global_attrs, ...
	              'VariableAttributes', var_attrs,    ...
	              'VarDatatypes',       vardatatypes, ...
	              'RecordBound',        recbound      ...
	            );
end